# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk12
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash) -t token

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою), если сборка упала
notifications:
  email:
    recipients:
      quaresma_08@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - CODECOV_TOKEN="f6147ac7-d96e-46fe-94d3-c458dfd7bfe9"